### ISSUE TITLE
Warn under some condition

### ISSUE THREAD

**Issue by saturnflyer** [searls/todo_or_die#12]
If the date is nearing, I'd like to get a warning in CI or something so that I can prepare.
Or if ... some condition is _almost_ met, I want to know it's coming.

I hope to work on this but I'm just leaving this issue as a placeholder or… the internet can implement this for me

**Comment by searls** [comment]
hmm… i guess an extra kwarg or two? `warn_if` and `warn_by`?

**Comment by czj** [comment]
To have an API that's almost the same, `warn_by` would be great.

```ruby
TodoOrDie("Remove this class", by: "2022-06-01", warn_by: "2022-05-01")
```

**Comment by searls** [comment]
yeah, I think `warn_by` and `warn_if` that mirror `by` and `if` as kwargs makes sense
