### ISSUE TITLE
Blow up when current branch is master

### ISSUE THREAD

**Issue by searls** [searls/todo_or_die#4]
One idea would be to blow up only if it's been merged to master. This is sneaky and evil from a CI perspective but could be one way to detect something you want to remove after a feature branch is merged but the dates aren't clear/meaningful.

I presume we'd do this by shelling out to git b/c lazy

**Comment by jasonkarns** [comment]
I think I'd rather prefer to use the proposed [`if` predicate ](https://github.com/searls/todo_or_die/issues/5) (or wrapping in a vanilla conditional) where the condition checks for "evidence of the PR being merged".

ie, if the feature PR adds a new method to an object, I'd rather write a todo on master that blows up if the desired method exists.

(I assume this is in cases where the PR in question couldn't take care of the todo item itself...)

**Comment by searls** [comment]
:+1: agree
